import type { Venue } from './types';

export const VENUES: Venue[] = [
  // === PART I: THE LABYRINTHS ===
  {
    id: 'u-sudu',
    name: 'U Sudu',
    address: 'Vodi\u010Dkova 10, Nov\u00E9 M\u011Bsto',
    year: 'Est. unknown',
    points: 10,
    badge: 'default',
    category: 'Labyrinthine / Gothic vaults / Multi-building',
    part: 1,
    partTitle: 'THE LABYRINTHS',
    partSubtitle: 'Bars where the architecture defies explanation and you will lose people in your group',
    description: 'The ground floor looks like a normal, slightly worn-out bar. You go downstairs. And then you keep going. Each room has a different exit that leads to another room, then another, then another \u2014 a labyrinth of Gothic vaults stretching beneath multiple buildings. A wine cellar in one chamber. Pool tables in the next. A DJ somewhere deeper. A quiet cave in the back where two people are having a conversation they started years ago. There is no map. You just keep discovering rooms. You will lose people in your group. That is part of it.',
    tags: ['Labyrinthine', 'Gothic vaults', 'Multi-building'],
    url: 'https://prague.eu/en/objevujte/vinarna-u-sudu/',
  },
  {
    id: 'u-krale-brabantskeho',
    name: 'U Kr\u00E1le Brabantsk\u00E9ho',
    address: 'Thunovsk\u00E1 15, Mal\u00E1 Strana',
    year: '1375',
    points: 10,
    badge: 'default',
    category: 'Medieval tavern / Royal passages / Candlelit',
    part: 1,
    partTitle: 'THE LABYRINTHS',
    partSubtitle: 'Bars where the architecture defies explanation and you will lose people in your group',
    description: 'Six hundred and fifty years old. Hidden passageways run beneath the bar \u2014 passages that Czech kings once used to slip in anonymously and drink among commoners, forgetting their royalty for a few hours. The underground level is lit entirely by candles and torches. No electric light. The dungeon atmosphere is total. You descend, you order a Pilsner Urquell, and you sit in the same vaulted stone room where smugglers and monarchs shared a table. Try to determine which tunnel the king used. You won\u2019t.',
    tags: ['Medieval tavern', 'Royal passages', 'Candlelit'],
    url: 'https://thirdeyetraveller.com/oldest-prague-medieval-tavern-krcma-brabant/',
  },
  {
    id: 'vinarna-v-cihelne',
    name: 'Vin\u00E1rna V Ciheln\u011B',
    address: 'Near Wenceslas Square, Nov\u00E9 M\u011Bsto',
    year: '\u2014',
    points: 5,
    badge: 'default',
    category: 'Wine labyrinth / Medieval passages / Multi-atmosphere',
    part: 1,
    partTitle: 'THE LABYRINTHS',
    partSubtitle: 'Bars where the architecture defies explanation and you will lose people in your group',
    description: 'A sprawling wine bar that connects the cellar rooms of several adjacent buildings through medieval passageways. The chambers were never designed to be one venue \u2014 they were separate ground floors, buried when Prague raised its streets, and the connections between buildings happened accidentally underground. Now it is a maze of candlelit rooms, each with its own atmosphere. One is crowded and loud. The next is dead silent, two strangers sharing a bottle of Moravian wine. You will lose your sense of direction. That is the point.',
    tags: ['Wine labyrinth', 'Medieval passages', 'Multi-atmosphere'],
    url: 'https://www.realpragueguides.com/blog/tours-to-pragues-medieval-underground-know-before-you-go',
  },

  // === PART II: THE VAULTS ===
  {
    id: 'u-fleku',
    name: 'U Flek\u016F',
    address: 'K\u0159emencova 11, Nov\u00E9 M\u011Bsto',
    year: '1499',
    points: 5,
    badge: 'default',
    category: 'Brewery since 1499 / Single dark lager / Stone archways',
    part: 2,
    partTitle: 'THE VAULTS',
    partSubtitle: 'Cellars with singular purpose \u2014 older than the buildings above them',
    description: 'One of Europe\u2019s oldest continuously operating taverns. The medieval cellar beneath the main beer hall has original stone archways and wooden tables worn smooth by five centuries of elbows. They brew one beer here \u2014 a dark 13-degree lager \u2014 and they have brewed it since before Columbus returned from his second voyage. The walls have absorbed more history than most museums. You do not come here for variety. You come here for the weight of the room.',
    tags: ['Brewery since 1499', 'Single dark lager', 'Stone archways'],
    url: 'https://en.wikipedia.org/wiki/U_Flek%C5%AF',
  },
  {
    id: 'u-kunstatu',
    name: 'U Kun\u0161t\u00E1tu',
    address: '\u0158et\u011Bzov\u00E1 3, Star\u00E9 M\u011Bsto',
    year: 'c. 1250',
    points: 10,
    badge: 'default',
    category: '13th century / Romanesque-Gothic / Former royal residence',
    part: 2,
    partTitle: 'THE VAULTS',
    partSubtitle: 'Cellars with singular purpose \u2014 older than the buildings above them',
    description: 'A cellar dating to the mid-thirteenth century \u2014 older than most European countries. Built by Bo\u010Dek of Kun\u0161t\u00E1t and Pod\u011Bbrady, a courtier at Prague Castle. Its most famous resident was King George of Pod\u011Bbrady, Bohemia\u2019s first Hussite king, who lived here while working as a bailiff in the Old Town. The Romanesque and Gothic chambers now serve as both a restaurant and an art gallery. When you sit in these rooms, you are sitting in the original street level of medieval Prague.',
    tags: ['13th century', 'Romanesque-Gothic', 'Former royal residence'],
    url: 'https://www.realpragueguides.com/blog/tours-to-pragues-medieval-underground-know-before-you-go',
  },
  {
    id: 'krcma',
    name: 'Kr\u010Dma',
    address: 'Jewish Quarter, Star\u00E9 M\u011Bsto',
    year: '\u2014',
    points: 5,
    badge: 'default',
    category: 'Jewish Quarter / Craft beer / Low vaults',
    part: 2,
    partTitle: 'THE VAULTS',
    partSubtitle: 'Cellars with singular purpose \u2014 older than the buildings above them',
    description: 'Not fully underground, but stepping inside feels like crossing a temporal boundary. The cellars are fantastically preserved \u2014 rough edges, low ceilings, the kind of stone that has been absorbing candlelight and conversation for half a millennium. Craft beer from Permon Brewery on tap. On fortunate evenings, live music fills the vaults. Watch your head in the doorways, or you will acquire the wrong kind of headache.',
    tags: ['Jewish Quarter', 'Craft beer', 'Low vaults'],
    url: 'https://www.expats.cz/czech-news/article/feast-game-of-thrones-style-at-pragues-medieval-taverns',
  },

  // === PART III: THE HIDDEN ===
  {
    id: 'black-angels-bar',
    name: 'Black Angel\u2019s Bar \u2014 "The Shrink"',
    address: 'Jungmannova 23, Nov\u00E9 M\u011Bsto',
    year: '\u2014',
    points: 10,
    badge: 'default',
    category: 'Speakeasy / Personalized cocktails / 1920s atmosphere',
    part: 3,
    partTitle: 'THE HIDDEN',
    partSubtitle: 'You have to know how to get in',
    description: 'Find the entrance by waiting for a red light, or by asking to see the Shrink. You descend into a cellar styled after the 1920s \u2014 sultry jazz, homemade bitters, dim amber light. They ask you questions about your mood and preferences, then build a personalized cocktail. Not medieval. But the energy of having to know the entry protocol, of being asked questions before you\u2019re served, of sitting in a room that feels slightly outside of normal time \u2014 that is the same energy the kings felt in their secret passages.',
    tags: ['Speakeasy', 'Personalized cocktails', '1920s atmosphere'],
    url: 'https://www.theinfatuation.com/prague/reviews/black-angels-bar',
  },
  {
    id: 'hemingway-bar',
    name: 'Hemingway Bar',
    address: 'Karol\u00EDny Sv\u011Btl\u00E9 26, Star\u00E9 M\u011Bsto',
    year: '\u2014',
    points: 10,
    badge: 'default',
    category: 'Absinthe ritual / Proper preparation / \u017Duf\u00E1nek spirits',
    part: 3,
    partTitle: 'THE HIDDEN',
    partSubtitle: 'You have to know how to get in',
    description: 'The place in Prague where absinthe is served correctly \u2014 not set on fire as a party trick, but diluted with ice water through a slotted spoon, the way it was consumed during the green hour of the nineteenth century. The atmosphere is old-school and sophisticated. Martin \u017Duf\u00E1nek, one of the country\u2019s finest distillers, has produced reproductions of historical absinthe recipes dating to the late eighteenth century. Some of those bottles find their way here. This is where the Green Fairy lives when she is being taken seriously.',
    tags: ['Absinthe ritual', 'Proper preparation', '\u017Duf\u00E1nek spirits'],
    url: 'https://www.lonelyplanet.com/czech-republic/prague/stare-mesto/nightlife/hemingway-bar/a/poi-dri/1255829/1323269',
  },
  {
    id: 'anonymous-bar',
    name: 'Anonymous Bar',
    address: 'Michalsk\u00E1 12, Star\u00E9 M\u011Bsto',
    year: '\u2014',
    points: 5,
    badge: 'default',
    category: 'Masked bartenders / Hidden menu / Internet culture',
    part: 3,
    partTitle: 'THE HIDDEN',
    partSubtitle: 'You have to know how to get in',
    description: 'The bartenders wear Guy Fawkes masks. The walls reference internet culture \u2014 Reddit, 4chan, early internet lore. The menu changes throughout the night: arrive early for the base offerings, stay late for the surprise menu with drinks hidden within the original listings. An unlikely pairing \u2014 medieval cellar architecture and digital-age subculture \u2014 that works precisely because Prague has always been a city where the underground and the counter-cultural are the same thing.',
    tags: ['Masked bartenders', 'Hidden menu', 'Internet culture'],
    url: 'https://www.getlostmagazine.com/category-highlight/unveil-yourself-at-anonymous-bar/',
  },

  // === PART IV: THE CAVERNS ===
  {
    id: 'punkva-caves',
    name: 'Punkva Caves & Macocha Abyss',
    address: 'Moravian Karst, near Brno',
    year: '\u2014',
    points: 20,
    badge: 'default',
    category: 'Underground river / 138m abyss / Boat passage',
    part: 4,
    partTitle: 'THE CAVERNS',
    partSubtitle: 'Beyond the city \u2014 into the earth itself',
    description: 'An underground river boat ride through a cave system decorated with stalactites and stalagmites, emerging at the bottom of the deepest abyss in Central Europe \u2014 one hundred and thirty-eight metres of sheer rock, open to the sky. The legend: an evil stepmother threw her stepson in. He survived. The villagers threw her in. She did not. A gondola takes you to the top. The whole journey feels like crossing the River Styx, and you may want to bring two coins for the boatman.',
    tags: ['Underground river', '138m abyss', 'Boat passage'],
    url: 'https://www.atlasobscura.com/places/macocha-abyss',
  },
  {
    id: 'vypustek-cave',
    name: 'Vypustek Cave',
    address: 'Near Brno, South Moravia',
    year: '\u2014',
    points: 25,
    badge: 'rare',
    category: 'WWII factory / Cold War bunker / Classified until 2001',
    part: 4,
    partTitle: 'THE CAVERNS',
    partSubtitle: 'Beyond the city \u2014 into the earth itself',
    description: 'Three layers of history stacked underground. First: a prehistoric shelter. Second: during World War II, the Germans installed concrete floors and electricity and used it as an underground airplane factory. Third: between 1961 and 1968, the Czechoslovak Army built a secret nuclear fallout shelter and command post inside the cave. It remained classified until 2001. You can walk through the sleeping quarters, the logistics hall, the command post. A Y-shaped tunnel containing the entire paranoid architecture of the twentieth century, buried inside the earth.',
    tags: ['WWII factory', 'Cold War bunker', 'Classified until 2001'],
    url: 'https://www.moravskykras.net/en/vypustek-cave.html',
  },
  {
    id: 'koneprusy-caves',
    name: 'Kon\u011Bprusy Caves',
    address: 'Bohemian Karst, near Beroun',
    year: '\u2014',
    points: 25,
    badge: 'rare',
    category: '400 million years old / Medieval forgery / Bat colonies',
    part: 4,
    partTitle: 'THE CAVERNS',
    partSubtitle: 'Beyond the city \u2014 into the earth itself',
    description: 'The longest cave system in the Czech Republic \u2014 over two kilometres, formed in Devonian limestone four hundred million years old. Dripstone formations called Kon\u011Bprusy roses are themselves over a million years old, created when Bohemia had a tropical climate. Deep inside, archaeologists found a secret medieval counterfeiting workshop where forgers struck fake silver Hussite coins. The caves are still inhabited \u2014 by bats, in winter.',
    tags: ['400 million years old', 'Medieval forgery', 'Bat colonies'],
    url: 'https://www.visitczechia.com/en-us/things-to-do/places/nature/caves/c-koneprusy-caves',
  },

  // === PART V: THE UNDERWORLD ===
  {
    id: 'zizkov',
    name: '\u017Di\u017Ekov',
    address: 'Prague 3',
    year: '\u2014',
    points: 5,
    badge: 'default',
    category: 'Counter-culture district / Pay-what-you-want / Giant babies',
    part: 5,
    partTitle: 'THE UNDERWORLD',
    partSubtitle: 'The counter-culture that lives beneath the surface in every sense',
    description: 'The neighborhood with the second-highest density of bars per capita in Europe, named after Jan \u017Di\u017Eka \u2014 a one-eyed Hussite general whose equestrian statue atop V\u00EDtkov Hill is the largest in the world. Begin at the Big Lebowski bar, where drinks are customer-priced. End at Pal\u00E1c Akropolis for live music in a space that feels like a Cold War bunker converted by artists who never left. Above it all, the \u017Di\u017Ekov Television Tower \u2014 with giant baby sculptures by David \u010Cern\u00FD crawling up the outside \u2014 watches the neighbourhood like a brutalist lighthouse.',
    tags: ['Counter-culture district', 'Pay-what-you-want', 'Giant babies'],
    url: 'https://www.atlasobscura.com/places/zizkov-tower',
  },
  {
    id: 'cross-club',
    name: 'Cross Club',
    address: 'Plyn\u00E1rn\u00ED 23, Hole\u0161ovice',
    year: '\u2014',
    points: 10,
    badge: 'default',
    category: 'Industrial / Kinetic sculpture / Multi-level',
    part: 5,
    partTitle: 'THE UNDERWORLD',
    partSubtitle: 'The counter-culture that lives beneath the surface in every sense',
    description: 'Multiple underground levels inside a former industrial building. Every surface is covered in kinetic metal sculptures, moving gears, and mechanical art built by local artists. It looks like the interior of a steampunk submarine having a fever dream. Live music, DJs, and you navigate between levels through what is technically a bar but functions as an immersive art installation that someone accidentally serves drinks inside.',
    tags: ['Industrial', 'Kinetic sculpture', 'Multi-level'],
    url: 'https://www.atlasobscura.com/places/cross-club',
  },
  {
    id: 'meetfactory',
    name: 'MeetFactory',
    address: 'Ke Skl\u00E1rn\u011B 15, Sm\u00EDchov',
    year: '\u2014',
    points: 10,
    badge: 'default',
    category: 'David \u010Cern\u00FD / Art factory / Post-revolution culture',
    part: 5,
    partTitle: 'THE UNDERWORLD',
    partSubtitle: 'The counter-culture that lives beneath the surface in every sense',
    description: 'A renovated factory in Sm\u00EDchov, now a multipurpose art space run by David \u010Cern\u00FD \u2014 the same artist responsible for the babies on the TV tower. Temporary tattoo workshops, screen printing sessions, avant-garde theatre, and whatever else the current residents have decided to try. In a neighbourhood where artists have been transforming abandoned industrial buildings since the Velvet Revolution, MeetFactory is the anchor. The underground here is not architectural. It is ideological.',
    tags: ['David \u010Cern\u00FD', 'Art factory', 'Post-revolution culture'],
    url: 'https://www.meetfactory.cz/en',
  },

  // === PART VI: THE WILD ===
  {
    id: 'river-surfing',
    name: 'River Surfing on the Vltava',
    address: 'North of the Hilton Hotel, Prague',
    year: '\u2014',
    points: 30,
    badge: 'rare',
    category: 'River surfing / Equipment provided / Hidden in plain sight',
    part: 6,
    partTitle: 'THE WILD',
    partSubtitle: 'Adventures above ground that carry the spirit of the underground',
    description: 'A standing wave on the Vltava River, in the centre of a landlocked Central European capital. Biko Adventures provides equipment and runs group sessions. You do not need to be experienced \u2014 only able to swim. Nobody expects to surf in Prague, which is exactly why it works. The wave is a relatively new development and draws none of the spectator crowds of Munich\u2019s Eisbachwelle. For now, it belongs to the people who know about it.',
    tags: ['River surfing', 'Equipment provided', 'Hidden in plain sight'],
    url: 'https://www.vlnystvanice.cz/english/vlny-stvanice',
  },
  {
    id: 'certovy-hlavy',
    name: '\u010Certovy Hlavy \u2014 The Devil\u2019s Heads',
    address: 'Near \u017Del\u00EDzy, two hours from Prague by train',
    year: '\u2014',
    points: 25,
    badge: 'rare',
    category: 'Disappearing sculptures / Forest hike / Time-limited',
    part: 6,
    partTitle: 'THE WILD',
    partSubtitle: 'Adventures above ground that carry the spirit of the underground',
    description: 'In the 1840s, a sculptor named V\u00E1clav Lev\u00FD carved enormous demonic faces into sandstone cliffs in the middle of a forest. They are ten metres tall. They have been weathering for a hundred and eighty years and will disappear entirely within fifty more. You hike through the woods to find them \u2014 no signs, no crowds, no gift shop. Nearby, the Kl\u00E1celka cave system holds reliefs of Czech historical figures carved into stone. The whole thing feels like stumbling onto something you were not supposed to find. You are, in a sense, on a deadline.',
    tags: ['Disappearing sculptures', 'Forest hike', 'Time-limited'],
    url: 'https://www.atlasobscura.com/places/the-devils-heads-zelizy-czechia',
  },
  {
    id: 'sapa-market',
    name: 'Sapa Market \u2014 Little Hanoi',
    address: 'Outskirts of Prague 4',
    year: '\u2014',
    points: 15,
    badge: 'default',
    category: 'Vietnamese community / Not a tourist attraction / Portal',
    part: 6,
    partTitle: 'THE WILD',
    partSubtitle: 'Adventures above ground that carry the spirit of the underground',
    description: 'During communism, Czechoslovakia ran a guest worker programme with Vietnam. Thousands came, stayed, raised families, and built a community. Sapa is one of the largest Vietnamese markets outside of Vietnam \u2014 a maze of food stalls, restaurants, shops, and cafes on the edge of Prague. It is not a tourist attraction. It is a functioning world. The pho is extraordinary. The bubble tea is correct. You come here to eat like you accidentally stepped through a portal.',
    tags: ['Vietnamese community', 'Not a tourist attraction', 'Portal'],
    url: 'https://www.atlasobscura.com/places/tttm-sapa',
  },

  // === PART VII: THE BONES ===
  {
    id: 'sedlec-ossuary',
    name: 'Sedlec Ossuary',
    address: 'Kutn\u00E1 Hora \u2014 one hour from Prague by train',
    year: 'c. 1400',
    points: 15,
    badge: 'blood',
    category: '40,000 skeletons / Bone chandelier / Night tours in summer',
    part: 7,
    partTitle: 'THE BONES',
    partSubtitle: 'Where the dead were arranged into art and then forgotten',
    description: 'A chandelier containing every bone in the human body. Skull garlands hung like birthday streamers. A full aristocratic coat of arms \u2014 including a raven pecking out a Turk\u2019s eye \u2014 rendered entirely in human remains. Between 40,000 and 70,000 skeletons, arranged by a woodcarver named Franti\u0161ek Rint in 1870 after a half-blind monk spent years stacking them into pyramids. The plague and the Hussite Wars filled this cemetery beyond capacity. In summer, they do candlelit night tours. The woman at the entrance says the same thing every time: Memento mori.',
    tags: ['40,000 skeletons', 'Bone chandelier', 'Night tours in summer'],
    url: 'https://www.atlasobscura.com/places/sedlec-ossuary',
  },
  {
    id: 'brno-ossuary',
    name: 'Brno Ossuary \u2014 St. James Church',
    address: 'Jakubsk\u00E9 n\u00E1m\u011Bst\u00ED, Brno',
    year: 'Discovered 2001',
    points: 20,
    badge: 'blood',
    category: '50,000 remains / Forgotten for 200 years / Public since 2012',
    part: 7,
    partTitle: 'THE BONES',
    partSubtitle: 'Where the dead were arranged into art and then forgotten',
    description: 'In 2001, workers repairing a street found rooms and tunnels filled floor-to-ceiling with human bones. Fifty thousand people. Five centuries of plague, cholera, the Thirty Years\u2019 War, and the Swedish siege of Brno. The stairway from the church nave to the crypt had been covered with a stone slab and forgotten \u2014 sealed and unknown for over two hundred years. Opened to the public only in 2012. Larger than Sedlec. Less artful, more raw. Somber music plays continuously.',
    tags: ['50,000 remains', 'Forgotten for 200 years', 'Public since 2012'],
    url: 'https://www.atlasobscura.com/places/brno-ossuary',
  },
  {
    id: 'krtiny-ossuary',
    name: 'Krtiny Ossuary',
    address: 'Church of the Blessed Virgin Mary, Moravia',
    year: '\u2014',
    points: 30,
    badge: 'rare',
    category: 'Sealed and forgotten / Rediscovered 1991 / Nearly unknown',
    part: 7,
    partTitle: 'THE BONES',
    partSubtitle: 'Where the dead were arranged into art and then forgotten',
    description: 'A tiny ossuary beneath a Baroque church. After the bones were placed inside, the entrances were sealed. Then it was forgotten entirely \u2014 lost for over a century until its rediscovery in 1991. Inside, they found the remains of the temple\u2019s founder, Abbot Matu\u0161ka, and reburied him in a decorative copper box. Approximately one thousand sets of remains. The skulls have been studied for medical insights. Almost no one visits. Almost no one knows it exists.',
    tags: ['Sealed and forgotten', 'Rediscovered 1991', 'Nearly unknown'],
    url: 'https://www.atlasobscura.com/places/krtiny-ossuary',
  },

  // === PART VIII: THE ERASED ===
  {
    id: 'ghost-church',
    name: 'Kostel Svat\u00E9ho Ji\u0159\u00ED \u2014 The Ghost Church',
    address: 'Lukov\u00E1, Western Bohemia',
    year: '\u2014',
    points: 25,
    badge: 'rare',
    category: 'Abandoned 1968 / Ghost sculptures / Sudeten memorial',
    part: 8,
    partTitle: 'THE ERASED',
    partSubtitle: 'Places that were meant to disappear \u2014 and the ones that refused',
    description: 'A fourteenth-century church that the congregation abandoned after the roof collapsed during a funeral in 1968. They believed it was cursed. Refused to enter. Held mass outside under the open sky. For forty years it decayed \u2014 everything movable was stolen: paintings, statues, the clock, the bell. Then a sculpture student named Jakub Hadrava filled the church with thirty plaster ghost figures, seated in the pews, hooded and faceless. The ghosts represent the expelled Sudeten Germans who built this church and were driven from this land after the war. The plan worked. Tourists came. They left money. The roof was repaired. But the ghosts remain. They are the congregation now.',
    tags: ['Abandoned 1968', 'Ghost sculptures', 'Sudeten memorial'],
    url: 'https://www.atlasobscura.com/places/haunted-ghost-church-kostel-svateho-jiri',
  },
  {
    id: 'lidice-memorial',
    name: 'Lidice Memorial',
    address: '12 miles northwest of Prague',
    year: '\u2014',
    points: 20,
    badge: 'blood',
    category: 'Erased 1942 / 82 bronze children / Rebuilt by miners\u2019 wages',
    part: 8,
    partTitle: 'THE ERASED',
    partSubtitle: 'Places that were meant to disappear \u2014 and the ones that refused',
    description: 'On June 10, 1942, the Nazis surrounded this mining village in retaliation for the assassination of Reinhard Heydrich. They shot all 173 men. Deported the women to Ravensbr\u00FCck. Sent 82 of the 88 children to gas chambers. Then they burned every building, dynamited the ruins, dug up the cemetery, killed the livestock, erased the roads, covered everything with soil, and planted crops. A radio broadcast announced: "The name of this community has been obliterated." It was not. British miners in Stoke-on-Trent donated their wages to rebuild it. Today, 82 bronze statues of children stand in an empty field. The last surviving woman of Lidice died in September 2024 at ninety-eight.',
    tags: ['Erased 1942', '82 bronze children', 'Rebuilt by miners\u2019 wages'],
    url: 'https://www.atlasobscura.com/places/the-lidice-children-lidice-czechia',
  },
  {
    id: 'sudetenland-ghost-villages',
    name: 'The Sudetenland Ghost Villages',
    address: 'Jesen\u00EDk, Brunt\u00E1l, \u0160umperk districts \u2014 the borderlands',
    year: '\u2014',
    points: 40,
    badge: 'rare',
    category: '~100 lost villages / No signs / The heaviest silence you will hear',
    part: 8,
    partTitle: 'THE ERASED',
    partSubtitle: 'Places that were meant to disappear \u2014 and the ones that refused',
    description: 'After the war, roughly three million ethnic Germans were expelled from the Czech borderlands. Entire communities vanished overnight. Approximately one hundred settlements in Moravia and Silesia were never resettled. What remains: moss-covered gravestones with German names in forgotten cemeteries. Crumbling church walls. Foundations being slowly consumed by forest. There are no signs. No visitor centres. No plaques. You drive into the mountains and find the outline of a village that stopped existing in 1946. The silence is the kind that has weight.',
    tags: ['~100 lost villages', 'No signs', 'The heaviest silence you will hear'],
    url: 'https://www.visitczechia.com/en-us/things-to-do/places/summer-sports/hiking-and-nordic-walking/n-abandoned-villages-bohemian-forest',
  },
];

export function getVenuesByPart(part: number): Venue[] {
  return VENUES.filter(v => v.part === part);
}

export const PART_COUNT = 8;
